Repository DFortun81/AllTheThings, pull requests merged in 2022-05, with the labels that each got.

#991 Legion leatherworking quest requirements
  .contrib/Parser/DATAS/02 - Outdoor Zones/08 Broken Isles/Professions.lua
Labels: Quest, Professions

#1002 Huge revamp to 'cost' calculations
  AllTheThings.lua
  locales/enUS.lua
Labels: Addon Bug, Suggestion, Collected Issue

#1011 Logic realignment
  AllTheThings.lua
  src/base.lua
Labels: Addon Bug
